import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import PageSeo from '../components/PageSeo.jsx';
import AccessibilityMenu from '../components/AccessibilityMenu.jsx';
import { supabase } from '../lib/supabase.js';
import { 
  FiEye, 
  FiPhone, 
  FiUnlock, 
  FiDatabase, 
  FiInfo, 
  FiCalendar, 
  FiClock, 
  FiArrowLeft,
  FiRefreshCw,
  FiCheck,
  FiAlertTriangle
} from 'react-icons/fi';
import { FaWhatsapp } from 'react-icons/fa';

// ההתחברות מתבצעת דרך Supabase Auth (email + סיסמה), משותפת עם ממשק הטכנאי.

export default function LogsPage() {
  const [authenticated, setAuthenticated] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loginError, setLoginError] = useState(false);
  const [loginLoading, setLoginLoading] = useState(false);

  const [loading, setLoading] = useState(true);
  const [logs, setLogs] = useState([]);
  const [dbError, setDbError] = useState(null);
  const [filterDays, setFilterDays] = useState('all'); // all, 1, 7, 30
  const [copiedSql, setCopiedSql] = useState(false);

  // SQL query for creating the site_analytics table
  const sqlCommand = `
-- 1. Create the site analytics table
CREATE TABLE IF NOT EXISTS public.site_analytics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event_type text NOT NULL, -- 'visit', 'whatsapp_click', 'phone_click'
    page_url text NOT NULL,
    user_agent text,
    referrer text
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.site_analytics ENABLE ROW LEVEL SECURITY;

-- 3. Create public policies for inserts and reads
CREATE POLICY "Allow anonymous insert" ON public.site_analytics 
    FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Allow anonymous read" ON public.site_analytics 
    FOR SELECT TO anon USING (true);
  `.trim();

  // Check login session via Supabase Auth
  useEffect(() => {
    document.documentElement.dir = 'rtl';
    window.scrollTo(0, 0);
    supabase.auth.getSession().then(({ data: { session } }) => {
      setAuthenticated(!!session);
    });
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setAuthenticated(!!session);
    });
    return () => subscription.unsubscribe();
  }, []);

  // Fetch logs from Supabase. Pass { silent: true } for background auto-refresh
  // so the screen doesn't flash a loading spinner on every poll.
  const fetchLogs = async ({ silent = false } = {}) => {
    if (!silent) setLoading(true);
    setDbError(null);
    try {
      const { data, error } = await supabase
        .from('site_analytics')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setLogs(data || []);
    } catch (err) {
      console.error('Error fetching analytics:', err);
      setDbError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!authenticated) return;
    fetchLogs();
    // רענון אוטומטי כל 20 שניות כדי להציג נתונים חדשים כמעט בזמן אמת
    const interval = setInterval(() => {
      fetchLogs({ silent: true });
    }, 20000);
    return () => clearInterval(interval);
  }, [authenticated]);

  const handleLoginSubmit = async (e) => {
    e.preventDefault();
    setLoginError(false);
    setLoginLoading(true);
    const { error } = await supabase.auth.signInWithPassword({
      email: email.trim(),
      password,
    });
    setLoginLoading(false);
    if (error) {
      setLoginError(true);
    }
    // בהצלחה — onAuthStateChange יעדכן את מצב ההתחברות.
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    setAuthenticated(false);
    setLogs([]);
  };

  const handleCopySql = () => {
    navigator.clipboard.writeText(sqlCommand);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 3000);
  };

  // Filter logs by date range
  const filteredLogs = logs.filter(log => {
    if (filterDays === 'all') return true;
    const logDate = new Date(log.created_at);
    const now = new Date();
    const diffTime = Math.abs(now - logDate);
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays <= parseInt(filterDays);
  });

  // Calculate statistics
  const totalVisits = filteredLogs.filter(l => l.event_type === 'visit').length;
  const totalWhatsapp = filteredLogs.filter(l => l.event_type === 'whatsapp_click').length;
  const totalPhone = filteredLogs.filter(l => l.event_type === 'phone_click').length;

  const formatDate = (isoStr) => {
    const d = new Date(isoStr);
    return d.toLocaleString('he-IL', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    });
  };

  // Login Screen render
  if (!authenticated) {
    return (
      <>
        <PageSeo title="ממשק סטטיסטיקות כניסה" description="סטטיסטיקות שימוש ויומני כניסה לאתר - israelfix" path="/logs" />
        <AccessibilityMenu stackAboveWhatsApp={false} />

        <div className="min-h-screen bg-[#F4F9FA] flex flex-col justify-center items-center p-4 font-sans selection:bg-[#78BCC4]/20 text-[#002C3E]" dir="rtl">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-[#002C3E] rounded-2xl flex items-center justify-center text-[#78BCC4] shadow-md">
              <FiDatabase className="w-6 h-6" strokeWidth={2.5} />
            </div>
            <span className="font-display text-2xl font-black tracking-tight text-[#002C3E]">
              israelfix<span className="text-[#F7444E]">.</span>
              <span className="text-xs bg-[#78BCC4]/20 text-[#2a8fa0] px-2.5 py-0.5 rounded-full mr-2 font-bold">אנליטיקה</span>
            </span>
          </div>

          <div className="max-w-md w-full bg-white rounded-3xl border border-[#002C3E]/10 p-8 shadow-xl text-right">
            <div className="text-center mb-6">
              <div className="w-16 h-16 bg-[#002C3E]/5 rounded-2xl flex items-center justify-center text-[#78BCC4] mx-auto mb-4 border border-[#78BCC4]/20 shadow-inner">
                <FiUnlock className="w-8 h-8" strokeWidth={2.5} />
              </div>
              <h2 className="text-2xl font-black text-[#002C3E]">סטטיסטיקת כניסות וקליקים</h2>
              <p className="text-[#002C3E]/50 text-sm mt-1">התחבר עם האימייל והסיסמה שלך כדי לצפות ביומנים ובכמות הכניסות</p>
            </div>

            <form onSubmit={handleLoginSubmit} className="space-y-5">
              <div>
                <label className="block text-sm font-bold text-[#002C3E] mb-2">אימייל</label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="הזן אימייל"
                  autoComplete="username"
                  dir="ltr"
                  className="w-full bg-[#F4F9FA] px-4 py-3.5 rounded-xl border border-[#002C3E]/20 outline-none focus:border-[#78BCC4] focus:bg-white transition-all text-[#002C3E] text-left text-sm placeholder:text-[#002C3E]/35"
                  autoFocus
                />
              </div>
              <div>
                <label className="block text-sm font-bold text-[#002C3E] mb-2">סיסמה</label>
                <input
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="הזן סיסמה"
                  autoComplete="current-password"
                  className="w-full bg-[#F4F9FA] px-4 py-3.5 rounded-xl border border-[#002C3E]/20 outline-none focus:border-[#78BCC4] focus:bg-white transition-all text-[#002C3E] text-right text-sm placeholder:text-[#002C3E]/35"
                />
              </div>

              {loginError && (
                <p className="text-[#F7444E] text-xs font-bold text-center bg-[#FEF2F2] py-2 rounded-lg border border-[#F7444E]/20">
                  אימייל או סיסמה שגויים. נסה שנית.
                </p>
              )}

              <button
                type="submit"
                disabled={loginLoading || !email || !password}
                className="w-full bg-[#002C3E] hover:bg-[#F7444E] text-white px-6 py-4 rounded-xl font-bold text-sm transition-all shadow-md shadow-[#002C3E]/10 disabled:opacity-50"
              >
                {loginLoading ? 'מאמת...' : 'כניסה למערכת'}
              </button>
            </form>
          </div>

          <footer className="mt-8 text-center text-xs text-[#002C3E]/30 font-medium">
            &copy; {new Date().getFullYear()} israelfix · סטטיסטיקת כניסות וקליקים
          </footer>
        </div>
      </>
    );
  }

  return (
    <>
      <PageSeo title="ממשק סטטיסטיקות כניסה" description="סטטיסטיקות שימוש ויומני כניסה לאתר - israelfix" path="/logs" />
      <AccessibilityMenu stackAboveWhatsApp={false} />

      <div className="min-h-screen bg-[#F4F9FA] font-sans selection:bg-[#78BCC4]/20 text-[#002C3E] pb-12" dir="rtl">
        {/* Header */}
        <header className="bg-[#002C3E] text-white py-5 shadow-md">
          <div className="container mx-auto px-5 md:px-6 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center text-[#78BCC4]">
                <FiDatabase className="w-5 h-5" />
              </div>
              <span className="font-display text-xl font-black text-white tracking-tight">
                israelfix<span className="text-[#F7444E]">.</span>
                <span className="text-xs bg-[#78BCC4]/20 text-[#78BCC4] px-2.5 py-0.5 rounded-full mr-2 font-bold">סטטיסטיקה ואנליטיקה</span>
              </span>
            </div>
            <div className="flex items-center gap-3">
              <button
                onClick={() => fetchLogs()}
                className="p-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-white/80 hover:text-white transition-colors"
                title="רענן נתונים"
              >
                <FiRefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
              </button>
              <button
                onClick={handleLogout}
                className="bg-[#F7444E] hover:bg-[#de3d46] text-white px-4 py-2 rounded-xl text-sm font-bold transition-colors"
              >
                התנתק
              </button>
              <Link
                to="/"
                className="flex items-center gap-1.5 text-white/70 hover:text-white transition-colors text-sm font-semibold mr-2"
              >
                <FiArrowLeft className="w-4 h-4" />
                חזרה לאתר
              </Link>
            </div>
          </div>
        </header>

        <main className="container mx-auto px-5 md:px-6 py-8">
          {/* DB error / missing table prompt */}
          {dbError ? (
            <div className="max-w-3xl mx-auto bg-white rounded-3xl border border-[#F7444E]/20 p-8 shadow-lg text-right mb-8">
              <div className="flex items-center gap-3 text-[#F7444E] mb-4">
                <FiAlertTriangle className="w-8 h-8 shrink-0" />
                <h3 className="text-xl font-black">טבלת האנליטיקה לא קיימת בבסיס הנתונים</h3>
              </div>
              <p className="text-base text-[#002C3E]/75 leading-relaxed mb-6 font-medium">
                על מנת להתחיל לתעד כניסות לאתר וקליקים על כפתורי הווטסאפ והטלפון, יש צורך ליצור טבלה מתאימה בשם <code className="bg-[#FEF2F2] text-[#F7444E] px-2 py-0.5 rounded font-mono font-bold text-sm">site_analytics</code> ב-Supabase.
                <br />
                באפשרותך להעתיק את פקודת ה-SQL הבאה ולהריץ אותה ישירות ב-<strong>SQL Editor</strong> של לוח הבקרה של Supabase.
              </p>

              <div className="bg-[#002C3E] rounded-2xl p-5 mb-5 font-mono text-left text-xs text-white overflow-x-auto relative shadow-inner">
                <pre>{sqlCommand}</pre>
                <button
                  onClick={handleCopySql}
                  className="absolute top-4 right-4 bg-white/10 hover:bg-white/20 text-[#78BCC4] px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5"
                >
                  {copiedSql ? (
                    <>
                      <FiCheck className="w-3.5 h-3.5 text-[#06d6a0]" />
                      הועתק!
                    </>
                  ) : (
                    'העתק קוד SQL'
                  )}
                </button>
              </div>

              <div className="flex items-center gap-3 bg-[#F4F9FA] p-4 rounded-xl border border-[#002C3E]/5 text-xs text-[#002C3E]/60 font-semibold leading-relaxed">
                <FiInfo className="w-5 h-5 text-[#78BCC4] shrink-0" />
                <span>
                  לאחר הרצת הקוד ב-Supabase, פשוט לחץ על כפתור ה"רענן" בראש העמוד הזה והנתונים יחלו להיטען ולהירשם באופן מיידי בכל כניסה של לקוח.
                </span>
              </div>
            </div>
          ) : (
            <>
              {/* Controls and filters */}
              <div className="flex flex-col sm:flex-row justify-between items-center bg-white p-4 rounded-2xl shadow-sm border border-[#002C3E]/5 mb-8 gap-4">
                <div className="text-right w-full sm:w-auto">
                  <h2 className="text-lg font-black text-[#002C3E]">סיכום פעילות משתמשים</h2>
                  <p className="text-xs text-[#002C3E]/50">כמות צפיות, לחיצות וואטסאפ והתקשרויות</p>
                </div>
                <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
                  <span className="text-xs font-bold text-[#002C3E]/60 ml-2">טווח זמן:</span>
                  {[
                    { id: 'all', label: 'הכל' },
                    { id: '1', label: 'היום' },
                    { id: '7', label: '7 ימים' },
                    { id: '30', label: '30 ימים' }
                  ].map(tab => (
                    <button
                      key={tab.id}
                      onClick={() => setFilterDays(tab.id)}
                      className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                        filterDays === tab.id
                          ? 'bg-[#002C3E] text-white shadow-md'
                          : 'bg-[#F4F9FA] text-[#002C3E]/60 hover:bg-[#E8F2F3] hover:text-[#002C3E]'
                      }`}
                    >
                      {tab.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Loader */}
              {loading ? (
                <div className="py-24 text-center">
                  <FiRefreshCw className="w-12 h-12 text-[#78BCC4] animate-spin mx-auto mb-4" />
                  <p className="text-[#002C3E]/60 font-bold text-sm">טוען נתונים משרת האנליטיקה...</p>
                </div>
              ) : (
                <>
                  {/* Status Cards */}
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                    {/* Visits */}
                    <div className="glass-card-light rounded-3xl p-6 shadow-sm border border-white/50 text-right flex items-center justify-between hover-tilt active-click smooth-interactive hover:shadow-md">
                      <div>
                        <span className="text-xs font-bold text-[#002C3E]/40 uppercase tracking-wider block mb-1">סך כניסות לאתר</span>
                        <span className="text-4xl font-black text-[#002C3E] tracking-tight">{totalVisits}</span>
                      </div>
                      <div className="w-14 h-14 bg-[#78BCC4]/10 text-[#78BCC4] rounded-2xl flex items-center justify-center shadow-inner">
                        <FiEye className="w-8 h-8" />
                      </div>
                    </div>

                    {/* WhatsApp Clicks */}
                    <div className="glass-card-light rounded-3xl p-6 shadow-sm border border-white/50 text-right flex items-center justify-between hover-tilt active-click smooth-interactive hover:shadow-md">
                      <div>
                        <span className="text-xs font-bold text-[#002C3E]/40 block mb-1">לחיצות וואטסאפ</span>
                        <span className="text-4xl font-black text-[#06d6a0] tracking-tight">{totalWhatsapp}</span>
                      </div>
                      <div className="w-14 h-14 bg-[#06d6a0]/10 text-[#06d6a0] rounded-2xl flex items-center justify-center shadow-inner">
                        <FaWhatsapp className="w-8 h-8" />
                      </div>
                    </div>

                    {/* Phone Clicks */}
                    <div className="glass-card-light rounded-3xl p-6 shadow-sm border border-white/50 text-right flex items-center justify-between hover-tilt active-click smooth-interactive hover:shadow-md">
                      <div>
                        <span className="text-xs font-bold text-[#002C3E]/40 block mb-1">לחיצות טלפון/התקשרות</span>
                        <span className="text-4xl font-black text-[#F7444E] tracking-tight">{totalPhone}</span>
                      </div>
                      <div className="w-14 h-14 bg-[#F7444E]/10 text-[#F7444E] rounded-2xl flex items-center justify-center shadow-inner">
                        <FiPhone className="w-7 h-7" />
                      </div>
                    </div>
                  </div>

                  {/* Summary Bar Chart Visual */}
                  <div className="bg-white p-6 rounded-3xl shadow-sm border border-[#002C3E]/5 mb-8 text-right">
                    <h3 className="text-lg font-black text-[#002C3E] mb-4">יחס אינטראקציה לעומת כניסות</h3>
                    
                    {totalVisits === 0 ? (
                      <p className="text-[#002C3E]/50 text-sm">אין עדיין מספיק נתונים להציג יחסי המרה.</p>
                    ) : (
                      <div className="space-y-5">
                        {/* Whatsapp Conversion */}
                        <div>
                          <div className="flex justify-between items-center text-xs font-bold mb-1.5">
                            <span>המרה לוואטסאפ (שלחו הודעה או קליק)</span>
                            <span className="text-[#06d6a0]">{((totalWhatsapp / totalVisits) * 100).toFixed(1)}%</span>
                          </div>
                          <div className="w-full bg-[#F4F9FA] h-3.5 rounded-full overflow-hidden border border-[#002C3E]/5 shadow-inner">
                            <div 
                              className="bg-[#06d6a0] h-full rounded-full transition-all duration-500 shadow-md animate-grow-bar"
                              style={{ width: `${Math.min(100, (totalWhatsapp / totalVisits) * 100)}%` }}
                            />
                          </div>
                        </div>

                        {/* Phone Conversion */}
                        <div>
                          <div className="flex justify-between items-center text-xs font-bold mb-1.5">
                            <span>המרה להתקשרות (קליק על חיוג)</span>
                            <span className="text-[#F7444E]">{((totalPhone / totalVisits) * 100).toFixed(1)}%</span>
                          </div>
                          <div className="w-full bg-[#F4F9FA] h-3.5 rounded-full overflow-hidden border border-[#002C3E]/5 shadow-inner">
                            <div 
                              className="bg-[#F7444E] h-full rounded-full transition-all duration-500 shadow-md animate-grow-bar"
                              style={{ width: `${Math.min(100, (totalPhone / totalVisits) * 100)}%` }}
                            />
                          </div>
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Logs Table */}
                  <div className="bg-white rounded-3xl shadow-sm border border-[#002C3E]/5 overflow-hidden">
                    <div className="p-6 border-b border-[#002C3E]/5 text-right flex justify-between items-center">
                      <div>
                        <h3 className="text-lg font-black text-[#002C3E]">יומן פעילות מפורט</h3>
                        <p className="text-xs text-[#002C3E]/50">תיעוד האירועים האחרונים שהתרחשו באתר</p>
                      </div>
                      <span className="text-xs bg-[#002C3E]/5 text-[#002C3E]/70 font-bold px-3 py-1.5 rounded-full">
                        מציג {filteredLogs.length} רשומות
                      </span>
                    </div>

                    {filteredLogs.length === 0 ? (
                      <div className="py-12 text-center text-[#002C3E]/50 text-sm font-semibold">
                        אין כרגע רשומות להצגה בטווח הזמן שנבחר.
                      </div>
                    ) : (
                      <div className="overflow-x-auto">
                        <table className="w-full text-right border-collapse">
                          <thead>
                            <tr className="bg-[#F4F9FA] text-[#002C3E]/60 text-xs font-bold border-b border-[#002C3E]/5">
                              <th className="p-4">סוג אירוע</th>
                              <th className="p-4">כתובת דף</th>
                              <th className="p-4">זמן אירוע</th>
                              <th className="p-4">דפדפן / מכשיר</th>
                              <th className="p-4">מקור (Referrer)</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-[#002C3E]/5 text-xs md:text-sm font-medium">
                            {filteredLogs.map((log) => (
                              <tr key={log.id} className="table-row-hover hover:bg-[#F4F9FA]/50 transition-colors">
                                <td className="p-4">
                                  {log.event_type === 'visit' && (
                                    <span className="inline-flex items-center gap-1.5 bg-[#78BCC4]/15 text-[#227e8d] px-2.5 py-1 rounded-full font-bold">
                                      <FiEye className="w-3.5 h-3.5" />
                                      כניסה לאתר
                                    </span>
                                  )}
                                  {log.event_type === 'whatsapp_click' && (
                                    <span className="inline-flex items-center gap-1.5 bg-[#06d6a0]/15 text-[#049d75] px-2.5 py-1 rounded-full font-bold">
                                      <FaWhatsapp className="w-3.5 h-3.5" />
                                      וואטסאפ
                                    </span>
                                  )}
                                  {log.event_type === 'phone_click' && (
                                    <span className="inline-flex items-center gap-1.5 bg-[#F7444E]/15 text-[#c92f38] px-2.5 py-1 rounded-full font-bold">
                                      <FiPhone className="w-3.5 h-3.5" />
                                      התקשרות
                                    </span>
                                  )}
                                </td>
                                <td className="p-4 font-mono text-xs">{log.page_url}</td>
                                <td className="p-4 text-[#002C3E]/70 flex items-center gap-1.5 mt-0.5">
                                  <FiCalendar className="text-[#78BCC4]" />
                                  <span>{formatDate(log.created_at)}</span>
                                </td>
                                <td className="p-4 text-[#002C3E]/50 text-xs max-w-xs truncate" title={log.user_agent}>
                                  {log.user_agent || '-'}
                                </td>
                                <td className="p-4 text-[#002C3E]/50 text-xs truncate max-w-[150px]" title={log.referrer}>
                                  {log.referrer || '-'}
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>
                </>
              )}
            </>
          )}
        </main>
      </div>
    </>
  );
}
